[project]
name = "credit-card"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "little-guang", email = "littleguangcode@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.5",
    "xlrd>=2.0.2",
]

[project.scripts]
credit-card = "credit_card:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
